// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD0TqKxhdGnqwWavtt-aJ5k2xwTiPKicQ',
    appId: '1:733321125455:web:6227f834a11dee31ded43a',
    messagingSenderId: '733321125455',
    projectId: 'flutter-demo-c2b58',
    authDomain: 'flutter-demo-c2b58.firebaseapp.com',
    storageBucket: 'flutter-demo-c2b58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwK6ohaVeJ4vQVSaizDb8cMKgea6In8y0',
    appId: '1:733321125455:android:1655fbc8c4cb08c8ded43a',
    messagingSenderId: '733321125455',
    projectId: 'flutter-demo-c2b58',
    storageBucket: 'flutter-demo-c2b58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ3SKuBtzCM1CJW6me6mhMtwTP11bCQKM',
    appId: '1:733321125455:ios:6d1ff37748b8c311ded43a',
    messagingSenderId: '733321125455',
    projectId: 'flutter-demo-c2b58',
    storageBucket: 'flutter-demo-c2b58.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ3SKuBtzCM1CJW6me6mhMtwTP11bCQKM',
    appId: '1:733321125455:ios:6d1ff37748b8c311ded43a',
    messagingSenderId: '733321125455',
    projectId: 'flutter-demo-c2b58',
    storageBucket: 'flutter-demo-c2b58.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD0TqKxhdGnqwWavtt-aJ5k2xwTiPKicQ',
    appId: '1:733321125455:web:778bd57a697681dfded43a',
    messagingSenderId: '733321125455',
    projectId: 'flutter-demo-c2b58',
    authDomain: 'flutter-demo-c2b58.firebaseapp.com',
    storageBucket: 'flutter-demo-c2b58.firebasestorage.app',
  );
}
